# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Use a stable version of checkout action
    - name: Set up Python
      uses: actions/setup-python@v5 # Use a stable version of setup-python
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: python -m pytest tests/
    - name: Lint with Flake8
      run: flake8 .
